# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Strange Case for Morisem"
license = "MIT"
licenselink = "https://github.com/aslemen/hugo-strange-case/LICENSE.md"
description = "A 2 column blog theme for Hugo using Bootstrap - inspired by the Jekyll theme Hyde by mdo"
homepage = "https://github.com/aslemen/hugo-strange-case"
tags = ["Blog", "Responsive", "Minimal", "Simple", "Clean", "Bootstrap"]
features = ["Blog", "Responsive", "Bootstrap"]
min_version = 0.53

[author]
	name = "Nori Hayashi"
	homepage = "https://www.hayashi-lin.net"

# If porting an existing theme
[original]
	name = "ExchangeRate-API"
	homepage = "https://www.exchangerate-api.com"
	repo = "https://github.com/ExchangeRate-API/strange-case"
